#!/bin/bash
# posthog-snapshot-loader.sh
# Reads ~/.claude/cache/posthog-snapshot.json and prints a markdown summary
# for inclusion in larger reports (e.g. /sprint-status, /eod-review, /daily).
#
# Output contract:
# - If snapshot does not exist: prints a one-line nudge ("📊 No PostHog snapshot…").
# - If snapshot exists and is < 14 days old: prints a structured markdown block
#   with critical findings, wins, and improvements.
# - If snapshot exists and is > 14 days old: prints a stale warning instead of
#   the full block, so callers don't quote outdated insights at users.
#
# The snapshot is generated by the /posthog-weekly skill. This loader is
# read-only: it never refreshes data. To refresh, the user runs /posthog-weekly.
#
# Output format is plain markdown so callers can either include it verbatim
# in a larger report or pipe it to another tool. Exit code is always 0 — this
# script never blocks the caller, even when the snapshot is missing or stale.

set -e

SNAPSHOT="$HOME/.claude/cache/posthog-snapshot.json"
STALE_DAYS="${POSTHOG_SNAPSHOT_STALE_DAYS:-14}"

# Case 1: no snapshot at all → silent nudge, single line
if [ ! -f "$SNAPSHOT" ]; then
  echo "📊 _No PostHog snapshot yet — run \`/posthog-weekly\` to generate one._"
  exit 0
fi

# Case 2: snapshot exists but is unreadable / not valid JSON
if ! jq empty "$SNAPSHOT" 2>/dev/null; then
  echo "⚠️ _PostHog snapshot at \`$SNAPSHOT\` is not valid JSON — re-run \`/posthog-weekly\` to regenerate._"
  exit 0
fi

# Compute snapshot age in days. The snapshot stores its timestamp as ISO 8601
# UTC. macOS `date -j -f` parses it; Linux `date -d` is the GNU equivalent.
TS=$(jq -r '.timestamp // empty' "$SNAPSHOT")
if [ -z "$TS" ]; then
  echo "⚠️ _PostHog snapshot has no timestamp — re-run \`/posthog-weekly\` to regenerate._"
  exit 0
fi

NOW_EPOCH=$(date +%s)
SNAP_EPOCH=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$TS" +%s 2>/dev/null \
          || date -d "$TS" +%s 2>/dev/null \
          || echo 0)

if [ "$SNAP_EPOCH" -eq 0 ]; then
  echo "⚠️ _PostHog snapshot timestamp \`$TS\` could not be parsed — re-run \`/posthog-weekly\`._"
  exit 0
fi

AGE_DAYS=$(( (NOW_EPOCH - SNAP_EPOCH) / 86400 ))

# Case 3: stale snapshot → short warning, no quoted findings
if [ "$AGE_DAYS" -gt "$STALE_DAYS" ]; then
  echo "⚠️ _PostHog snapshot is **${AGE_DAYS} days old** (stale > ${STALE_DAYS}d). Run \`/posthog-weekly\` to refresh before quoting._"
  exit 0
fi

# Case 4: fresh snapshot → full block
PROJECT_NAME=$(jq -r '.project_name // "PostHog"' "$SNAPSHOT")
PROJECT_URL=$(jq -r '.project_url // empty' "$SNAPSHOT")

echo "## 📊 PostHog Insights — ${PROJECT_NAME}"
echo ""
echo "_Snapshot from ${AGE_DAYS} day(s) ago — generated by \`/posthog-weekly\`_"
echo ""

# Critical findings — most important, always shown first
CRITICAL_COUNT=$(jq -r '.critical_findings | length' "$SNAPSHOT")
if [ "$CRITICAL_COUNT" -gt 0 ]; then
  echo "### 🚨 Critical findings"
  jq -r '.critical_findings[] | "- \(.)"' "$SNAPSHOT"
  echo ""
fi

# Regressions / anomalies
REGRESSION_COUNT=$(jq -r '.regressions // [] | length' "$SNAPSHOT")
if [ "$REGRESSION_COUNT" -gt 0 ]; then
  echo "### 📉 Regressions & anomalies"
  jq -r '.regressions[] | "- \(.)"' "$SNAPSHOT"
  echo ""
fi

# Wins
WIN_COUNT=$(jq -r '.wins // [] | length' "$SNAPSHOT")
if [ "$WIN_COUNT" -gt 0 ]; then
  echo "### ✅ Wins"
  jq -r '.wins[] | "- \(.)"' "$SNAPSHOT"
  echo ""
fi

# Improvement opportunities
IMPROVEMENT_COUNT=$(jq -r '.improvements // [] | length' "$SNAPSHOT")
if [ "$IMPROVEMENT_COUNT" -gt 0 ]; then
  echo "### 🎯 Improvement opportunities"
  jq -r '.improvements[] | "- \(.)"' "$SNAPSHOT"
  echo ""
fi

# Project link if available
if [ -n "$PROJECT_URL" ]; then
  echo "_Project: <${PROJECT_URL}>_"
  echo ""
fi

echo "_For deeper analysis, run \`/posthog-weekly\` to refresh this snapshot._"

exit 0
